routes/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    session,
    flash,
)

from models.user import User

from routes import current_user

from utils import log


main = Blueprint('auth', __name__)

@main.route('/')
def index():
    return render_template('/auth/registerLogin.html')


@main.route('/loginout', methods=['POST'])
def login_out():
    form = request.form
    user = current_user()
    user_id = form.get('id', None)
    if user_id is not None:
        user_id = int(user_id)
        if user.id == user_id:
            session.pop('user_id', None)
            return redirect(url_for('.index'))    
    flash('未成功退出')
    return redirect(url_for('user.index', username=user.username))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    new_user = User.register(form)
    if new_user is  None:
        flash('未注册成功， 用户名不合法或已被注册')
    else:
        flash('注册成功, 尝试登入吧')
    return redirect(url_for('.index'))


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    user = User.validate_login(form)
    if user is None:
        flash('登入失败，用户名或密码不正确')
        return redirect(url_for('.index'))
    else:
        session['user_id'] = user.id
        session.permanent = True
        username = user.__dict__['username']
        return redirect(url_for('user.index', username=username))

routes/index.py
from flask import (
    Blueprint,
    render_template,
    request,
)

from models.post import Post
from models.board import Board
from models import Pagination

from utils import (
    log,
    find_all_and_separate,
)


main = Blueprint('index', __name__)

@main.route('/')
def index():
    boards = Board.all()
    # you can set the quantity of unreplied_post by list slicing
    unreplied_posts = [p for p in Post.cache_all() if len(p.replies()) == 0]
    board_name = request.args.get('tab', '全部')
    # current_page is str passed from url
    # page 1 by default
    current_page = int(request.args.get('page', 1))
    if board_name == '全部':
        # top_posts = Post.find_all(top=True)
        # ordinary_posts = Post.find_all(top=False)
        # for performance
        ordinary_posts = Post.cache_all()
        top_posts = find_all_and_separate(ordinary_posts, top=True)
        top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
        ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
        sorted_posts = top_posts + ordinary_posts
    else:
        board = Board.find_by(name=board_name)
        if board is not None:
            # posts = Post.find_all(board_id=board.id)
            # top_posts = [p for p in posts if p.top == True]
            # ordinary_posts = [p for p in posts if p.top == False]
            # for performance
            ordinary_posts = Post.find_all(board_id=board.id)
            top_posts = find_all_and_separate(ordinary_posts, top=True)
            top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
            ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
            sorted_posts = top_posts + ordinary_posts
            # print('sorted_posts', len(sorted_posts))
        else:
            # in order to keep the consistency down here
            # we give the sorted_posts empty list
            sorted_posts = []
    page = Pagination(len(sorted_posts), current_page)
    data = page.data_by_page(sorted_posts)
    return render_template('index.html', data=data, page=page, unreplied_posts=unreplied_posts, boards=boards)

routes/post.py
import json

from flask import (
    Blueprint,
    request,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
)

from models.post import Post
from models.board import Board

from routes import current_user

from utils import log


main = Blueprint('post', __name__)

@main.route('/new', methods=['GET', 'POST'])
def new():
    if request.method == 'POST':
        user = current_user()
        if user is not None:
            form = request.form
            user_id = user.__dict__['id']
            # plus user_id on his post
            new_post = Post.new(form, user_id=user_id)
            new_post.hold()
            return redirect(url_for('.detail', id=new_post.id))
        else:
            flash('未登入， 不能发帖哦')
    boards = Board.all()
    return render_template('post/new.html', boards=boards)


@main.route('/delete', methods=['POST'])
def delete():
    post_id = request.args.get('id', None)
    user = current_user()
    if post_id is not None:
        post_id = int(post_id)
        post = Post.find_by(id=post_id)
        if post is not None and post.user_id == user.id:
            p = Post.delete(id=post_id)
            return json.dumps(p.__dict__, ensure_ascii=False)
    return redirect(url_for('user.index', username=user.username))


@main.route('/detail/<int:id>')
def detail(id):
    post = Post.find_by(id=id)
    if post is not None:
        post.auto_increment_views()
        replies = post.replies()
        return render_template('post/detail.html', post=post, replies=replies)
    else:
        return abort(404)

routes/user.py
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    send_from_directory,
    redirect,
    abort,
)

from models.user import User
from models.post import Post
from models.reply import Reply

import os

from werkzeug.utils import secure_filename

from config import upload_folder

from utils import log

from routes import (
    allowed_file,
    current_user,
)


main = Blueprint('user', __name__)

@main.route('/<string:username>')
def index(username):
    user = User.find_by(username=username)
    if user is not None:
        is_self = bool(current_user() is not None and current_user().id == user.id)
        posts = Post.find_all(user_id=user.id)
        replies = Reply.find_all(user_id=user.id)
        return render_template('user/profile.html', user=user, is_self=is_self, posts=posts, replies=replies)
    else:
        return abort(404)


@main.route('/signature/update', methods=['POST'])
def update_signature():
    form = request.form
    user = User.find_by(id=int(form.get('id')))
    if user is not None:
        user.signature = form.get('signature', user.signature)
        user.hold()
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/add', methods=['POST'])
def upload_headportrait():
    file = request.files['file']
    user = current_user()
    if file and allowed_file(file.filename):
        # not consider the conditon filename is not secure 
        filename = secure_filename(file.filename)
        user_id = user.__dict__['id']
        filename = filename.rsplit('.', 1)[0] +  str(user_id) + '.' + filename.rsplit('.', 1)[1]
        file.save(os.path.join(upload_folder, filename))
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/<int:u_id>')
def headportrait(u_id):
    file_list = os.listdir(upload_folder)
    for file in file_list:
        # do't forget turn to int 
        if u_id == int(file.rsplit('.', 1)[0][-1]):
            return send_from_directory(upload_folder, file)
    return abort(404)

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club专业的问答社区</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <!-- navbar -->
    <div class='navbar'>
        <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href="{{ url_for('index.index') }}">
                <img style="HEIGHT: inherit" src="{{ url_for('static', filename='1170859.gif') }}" />
            </a>
            <!-- call google search -->
            <form id='search_form' class='navbar-search' action="http://www.google.com/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('index.index') }}">首页</a></li>
                
                <li><a href='/getstart'>新手入门</a></li>
                <li><a href='/api'>API</a></li>
                
                <li><a href="/about" target="">关于</a></li>
                
                <li><a href="{{ url_for('auth.index') }}">注册</a></li>
                <li><a href="{{ url_for('auth.index') }}">登录</a></li>
            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
        </div>
    </div>
    <div id="main">
        <div id="sidebar">
            <div class="panel">
                <div class="inner">
                    <a href="{{ url_for('post.new') }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>无人回复的话题</span>
                </div>
                <div class='inner'>
                    <ul class="unstyled">
                        {% for p in unreplied_posts %}
                        <li>
                            <div>
                                <a class='dark topic_title' href="{{ url_for('post.detail', id=p.id) }}" title="{{ p.title }}">{{ p.title }}</a>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="{{ url_for('.index') }}"class="topic-tab">全部</a>
                    {% for b in boards%}
                    <a href="{{ url_for('.index', tab=b.name) }}"class="topic-tab"> {{ b.name }} </a>
                    <!-- do't hard code -->
                    <!-- <a href="/?tab={{ b.name }}"class="topic-tab"> {{ b.name }} </a> -->
                    {% endfor %}
                </div>
                <div class="inner post">
                    {% if data | count == 0 %}
                        <p>无话题</p>
                    {% else %}
                        <div class="topic_list">
                        {% for p in data %}
                            <div class="cell">
                                <a class="user_avatar pull-left" href="{{ url_for('user.index', username=p.user().username ) }}">
                                    <img src="{{ url_for('user.headportrait', u_id=p.user().id) }}" title="{{ p.user().username}}"/>
                                </a>
                                <span class="reply_count pull-left">
                                    <span class="count_of_replies" title="回复数">
                                        {{ p.replies() | length }}
                                    </span>
                                    <span class="count_seperator">/</span>
                                    <span class="count_of_visits" title='点击数'>
                                        {{ p.views }}
                                    </span>
                                </span>
                                <span class='last_time pull-right'>
                                    <span class="last_active_time"> {{ p.format_ct() }} </span>
                                </span>
                                <div class="topic_title_wrapper">
                                    {% if p.top == true %}
                                        <span class='put_top'>置顶</span>
                                    {% else %}
                                        <span class='topiclist-tab'> {{ p.board().name }} </span>
                                    {% endif %}
                                    <a class="topic_title" href="{{ url_for('post.detail', id=p.id) }}">
                                        {{ p.title }}
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                        <div class='pagination' current_page='{{ page.current_page }}'>
                        <ul>
                            <li><a href="{{ url_for('.index', tab=request.args.get('tab', '全部'), page=1) }}">«</a></li>
                            <!-- do not hard code is much better -->
                            <!-- <li><a href="/?tab={{ request.args.get('tab', '全部') }}&page=1">«</a></li> -->
                            {% if page.previous_page() %}
                            <li><a href="{{ url_for('.index', tab=request.args.get('tab', '全部'), page=page.previous_page()) }}">{{ page.previous_page() }}</a></li>
                            <!-- <li><a href="/?tab={{ request.args.get('tab', '全部') }}&page={{ page.previous_page() }}">{{ page.previous_page() }}</a></li> -->
                            {% else %}
                            <li><a>...</a></li>
                            {% endif %}

                            <li><a href="{{ url_for('.index', tab=request.args.get('tab', '全部'), page=page.current_page) }}">{{ page.current_page }}</a></li>
                            <!-- <li><a href="/?tab={{ request.args.get('tab', '全部') }}&page={{ page.current_page }}">{{ page.current_page }}</a></li> -->
                            
                            {% if page.next_page() %}
                            <li><a href="{{ url_for('.index', tab=request.args.get('tab', '全部'), page=page.next_page()) }}">{{ page.next_page() }}</a></li>
                            <!-- <li><a href="/?tab={{ request.args.get('tab', '全部') }}&page={{ page.next_page() }}">{{ page.next_page() }}</a></li> -->
                            {% else %}
                            <li><a>...</a></li>
                            {% endif %}
                            <li><a href="{{ url_for('.index', tab=request.args.get('tab', '全部'), page=page.total_page) }}">»</a></li>
                            <!-- <li><a href="/?tab={{request.args.get('tab', '全部')}}&page={{ page.total_page }}">»</a></li> -->
                        </ul>
                        </div>
                    {% endif %}
                    <script>
                        $(document).ready(function () {
                        var $nav = $('.pagination');
                        var current_page = $nav.attr('current_page');
                        if (current_page) {
                            $nav.find('li').each(function () {
                            var $li = $(this);
                            var $a = $li.find('a');
                            if ($a.html() == current_page) {
                                $li.addClass('active');
                                $a.removeAttr('href');
                            }
                            });
                        }
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
<script>
    (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
    })();
</script>
</body>
</html>