models/post.py
import time
import json

from models import Mongo
from models.user import User
from models.reply import Reply
from models.board import Board
from models.cache import (
    MemoryCache,
    RedisCache,
)

from utils import log


class Post(Mongo):
    __fields__ = Mongo.__fields__ + [
        ('title', str, ''),
        ('content', str, ''),
        ('views', int, 0),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('top', bool, False),
    ]

    should_update_all = True
    # 1. memory cache
    # memory_cache = MemoryCache()
    # 2. redis cache
    redis_cache = RedisCache()

    def to_json(self):
        d = dict()
        for k in self.__class__.__fields__:
            key = k[0]
            if not key.startswith('_'):
                d[key] = getattr(self, key)
        return json.dumps(d)

    @classmethod
    def from_json(cls, j):
        d = json.loads(j)
        instance = cls()
        for k, v in d.items():
            setattr(instance, k, v)
        return instance

    @classmethod
    def all_delay(cls):
        # supposing this's a time consuming operating
        # time.sleep(3)
        return cls.all()

    def hold(self):
        super().hold()
        self.__class__.should_update_all = True

    @classmethod
    def cache_all(cls):
        # 1.memory cache
        # if cls.should_update_all is True:
        #     log('should_update_all')
        #     cls.memory_cache.set('post_all', cls.all_delay())
        #     cls.should_update_all = False
        # return cls.memory_cache.get('post_all')
        # 2. redis cache
        if cls.should_update_all:
            log('should_update_all')
            cls.redis_cache.set('post_all', json.dumps([cls.to_json(i) for i in cls.all_delay()]))
            cls.should_update_all = False
        j = json.loads(cls.redis_cache.get('post_all'))
        return [cls.from_json(i) for i in j]

    @classmethod
    def find_all(cls, **kwargs):
        for k, v in kwargs.items():
            key = k
            value = v
        posts = cls.cache_all()
        return [p for p in posts if getattr(p, key) == value]

    def user(self):
        user = User.find_by(id=self.user_id)
        return user

    def board(self):
        board = Board.find_by(id=self.board_id)
        return board

    def auto_increment_views(self):
        self.__dict__['views'] += 1
        self.hold()

    def replies(self):
        r = Reply.find_all(post_id=self.id)
        return r

routes/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    session,
    flash,
)

from models.user import User

from routes import current_user

from utils import log


main = Blueprint('auth', __name__)

@main.route('/')
def index():
    return render_template('/auth/registerLogin.html')


@main.route('/loginout', methods=['POST'])
def login_out():
    form = request.form
    user = current_user()
    user_id = form.get('id', None)
    if user_id is not None:
        user_id = int(user_id)
        if user.id == user_id:
            session.pop('user_id', None)
            return redirect(url_for('.index'))    
    flash('未成功退出')
    return redirect(url_for('user.index', username=user.username))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    new_user = User.register(form)
    if new_user is  None:
        flash('未注册成功， 用户名不合法或已被注册')
    else:
        flash('注册成功, 尝试登入吧')
    return redirect(url_for('.index'))


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    user = User.validate_login(form)
    if user is None:
        flash('登入失败，用户名或密码不正确')
        return redirect(url_for('.index'))
    else:
        session['user_id'] = user.id
        session.permanent = True
        username = user.__dict__['username']
        return redirect(url_for('user.index', username=username))

routes/index.py
from flask import (
    Blueprint,
    render_template,
    request,
)

from models.post import Post
from models.board import Board
from models import Pagination

from utils import (
    log,
    find_all_and_separate,
)


main = Blueprint('index', __name__)

@main.route('/')
def index():
    boards = Board.all()
    # you can set the quantity of unreplied_post by list slicing
    unreplied_posts = [p for p in Post.cache_all() if len(p.replies()) == 0]
    board_name = request.args.get('tab', '全部')
    # current_page is str passed from url
    # page 1 by default
    current_page = int(request.args.get('page', 1))
    if board_name == '全部':
        # top_posts = Post.find_all(top=True)
        # ordinary_posts = Post.find_all(top=False)
        # for performance
        ordinary_posts = Post.cache_all()
        top_posts = find_all_and_separate(ordinary_posts, top=True)
        top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
        ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
        sorted_posts = top_posts + ordinary_posts
    else:
        board = Board.find_by(name=board_name)
        if board is not None:
            # posts = Post.find_all(board_id=board.id)
            # top_posts = [p for p in posts if p.top == True]
            # ordinary_posts = [p for p in posts if p.top == False]
            # for performance
            ordinary_posts = Post.find_all(board_id=board.id)
            top_posts = find_all_and_separate(ordinary_posts, top=True)
            top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
            ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
            sorted_posts = top_posts + ordinary_posts
            # print('sorted_posts', len(sorted_posts))
        else:
            # in order to keep the consistency down here
            # we give the sorted_posts empty list
            sorted_posts = []
    page = Pagination(len(sorted_posts), current_page)
    data = page.data_by_page(sorted_posts)
    return render_template('index.html', data=data, page=page, unreplied_posts=unreplied_posts, boards=boards)

routes/post.py
import json

from flask import (
    Blueprint,
    request,
    render_template,
    redirect,
    url_for,
    flash,
    abort,
)

from models.post import Post
from models.board import Board

from routes import current_user

from utils import log


main = Blueprint('post', __name__)

@main.route('/new', methods=['GET', 'POST'])
def new():
    if request.method == 'POST':
        user = current_user()
        if user is not None:
            form = request.form
            user_id = user.__dict__['id']
            # plus user_id on his post
            new_post = Post.new(form, user_id=user_id)
            new_post.hold()
            return redirect(url_for('.detail', id=new_post.id))
        else:
            flash('未登入， 不能发帖哦')
    boards = Board.all()
    return render_template('post/new.html', boards=boards)


@main.route('/delete', methods=['POST'])
def delete():
    post_id = request.args.get('id', None)
    user = current_user()
    if post_id is not None:
        post_id = int(post_id)
        post = Post.find_by(id=post_id)
        if post is not None and post.user_id == user.id:
            p = Post.delete(id=post_id)
            return json.dumps(p.__dict__, ensure_ascii=False)
    return redirect(url_for('user.index', username=user.username))


@main.route('/detail/<int:id>')
def detail(id):
    post = Post.find_by(id=id)
    if post is not None:
        post.auto_increment_views()
        replies = post.replies()
        return render_template('post/detail.html', post=post, replies=replies)
    else:
        return abort(404)

routes/reply.py
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    flash,
)

from routes import current_user

from models.reply import Reply

from utils import log

main = Blueprint('reply', __name__)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    user = current_user()
    if user is not None:
        user_id = user.__dict__['id']
        new_reply = Reply.new(form, user_id=user_id)
        new_reply.hold()
    else:
        flash('登入后才能回复')
    return redirect(url_for('post.detail', id=form.get('post_id')))

routes/user.py
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    send_from_directory,
    redirect,
    abort,
)

from models.user import User
from models.post import Post
from models.reply import Reply

import os

from werkzeug.utils import secure_filename

from config import upload_folder

from utils import log

from routes import (
    allowed_file,
    current_user,
)


main = Blueprint('user', __name__)

@main.route('/<string:username>')
def index(username):
    user = User.find_by(username=username)
    if user is not None:
        is_self = bool(current_user() is not None and current_user().id == user.id)
        posts = Post.find_all(user_id=user.id)
        replies = Reply.find_all(user_id=user.id)
        return render_template('user/profile.html', user=user, is_self=is_self, posts=posts, replies=replies)
    else:
        return abort(404)


@main.route('/signature/update', methods=['POST'])
def update_signature():
    form = request.form
    user = User.find_by(id=int(form.get('id')))
    if user is not None:
        user.signature = form.get('signature', user.signature)
        user.hold()
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/add', methods=['POST'])
def upload_headportrait():
    file = request.files['file']
    user = current_user()
    if file and allowed_file(file.filename):
        # not consider the conditon filename is not secure 
        filename = secure_filename(file.filename)
        user_id = user.__dict__['id']
        filename = filename.rsplit('.', 1)[0] +  str(user_id) + '.' + filename.rsplit('.', 1)[1]
        file.save(os.path.join(upload_folder, filename))
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/<int:u_id>')
def headportrait(u_id):
    file_list = os.listdir(upload_folder)
    for file in file_list:
        # do't forget turn to int 
        if u_id == int(file.rsplit('.', 1)[0][-1]):
            return send_from_directory(upload_folder, file)
    return abort(404)

templates/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club专业的问答社区</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <!-- navbar -->
    <div class='navbar'>
        <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href="{{ url_for('index.index') }}">
                <img style="HEIGHT: inherit" src="{{ url_for('static', filename='1170859.gif') }}" />
            </a>
            <!-- call google search -->
            <form id='search_form' class='navbar-search' action="http://www.google.com/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('index.index') }}">首页</a></li>
                
                <li><a href='/getstart'>新手入门</a></li>
                <li><a href='/api'>API</a></li>
                
                <li><a href="/about" target="">关于</a></li>
                
                <li><a href="{{ url_for('auth.index') }}">注册</a></li>
                <li><a href="{{ url_for('auth.index') }}">登录</a></li>
            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
        </div>
    </div>

    <div id="main">
        <div id="content">
            <div class='panel'>
                <div class='header topic_header'>
                    <span class="topic_full_title">
                        {{ post.title }}
                    </span>
                    <div class="changes">
                        <span>发布于 {{ post.format_ct() }}</span>
                        <span>
                            作者
                            <a href="{{ url_for('user.index', username=post.user().username) }}">{{ post.user().username }}</a>
                        </span>
                        <span>
                            {{ post.views }} 次浏览
                        </span>
                        <span>
                        来自 {{ post.board().name }}
                        </span>
                    </div>
                </div>
                <div class='inner topic'>
                    <div class='topic_content'>
                        <div class="markdown-text">
                            {{ post.content }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ replies | count }} 回复
                </span>
            </div>
            {% for r in replies %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <a href="{{ url_for('user.index', username=r.user().username) }}" class="user_avatar">
                        <img src="{{ url_for('user.headportrait', u_id=r.user().id) }}"
                            title="{{ r.user().username }}"/>
                    </a>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ r.user().username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 • {{ r.format_ct() }}
                        </a>
                    </div>
                    <div class='user_action'>
                        <span>
                            <i class="fa up_btnfa-thumbs-o-upinvisible" title="喜欢"></i>
                            <span class="up-count">
                            </span>
                        </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">
                        {{ r.content }}
                    </div>
                </div>
            </div>
            {% endfor %}
            <div>
                <form action="{{ url_for('reply.add') }}" method="post">
                    <input type="hidden" name="post_id" value="{{ post.id }}">
                    <textarea name="content"></textarea>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button>添加回复</button>
                </form>
            </div>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
    </div>
</body>
</html>

templates/post/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>bbs club专业的问答社区</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <link rel="stylesheet" href="/static/lib/editor/editor.css">
  <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
  <script src="/static/lib/jquery-3.0.0.min.js"></script>
  <script src="/static/lib/markdownit.js"></script>
  <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
  <script src="/static/lib/editor/editor.js"></script>
  <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
  <!-- navbar -->
  <div class='navbar'>
    <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href="{{ url_for('index.index') }}">
          <img style="HEIGHT: inherit" src="{{ url_for('static', filename='1170859.gif') }}" />
      </a>
      <!-- call google search -->
      <form id='search_form' class='navbar-search' action="http://www.google.com/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href="{{ url_for('index.index') }}">首页</a></li>
        
        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>
        
        <li><a href="/about" target="">关于</a></li>
        
        <li><a href="{{ url_for('auth.index') }}">注册</a></li>
        <li><a href="{{ url_for('auth.index') }}">登录</a></li>
      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="panel">
        <div class="inner post">
          <form id="create_topic_form" method="post" action="{{ url_for('.new') }}">
            <fieldset>
              <span class="tab-selector">选择版块:</span>
              <select name="board_id" id="board" required>
                <option value="">请选择</option>
                {% for b in boards %}
                  <option value="{{ b.id }}">{{ b.name }}</option>
                {% endfor %}
                </option>
              </select>
              <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
              <div class='markdown_editor in_editor'>
                <div class='markdown_in_editor'>
                  <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                  <div class='editor_buttons'>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                  </div>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
  <script>
    (function () {
      var editor = new Editor();
      editor.render($('.editor')[0]);
    })();
  </script>
</body>
</html>