models/user.py
import hashlib

from utils import log
from config import salt

from models import (
    Mongo,
    Role,
)

from models.mail import Mail


class User(Mongo, Role):
    __fields__ = Mongo.__fields__ + [
        ('permissions', int, 1),
        ('username', str, ''),
        ('password', str, ''),
        ('signature', str, ''),
    ]

    @classmethod
    def validate_login(cls, form):
        username = form.get('username')
        password = form.get('password')
        u = cls.find_by(username=username)
        if u is None:
            return None
        elif u.__dict__['password'] == cls.salted_password(password):
            return u
        else:
            return None

    @classmethod
    def register(cls, form):
        username = form.get('username', '')
        password = form.get('password', '')
        if len(username) > 0 and User.find_by(username=username) is None:
            new_user = cls.new(form)
            new_user.password = cls.salted_password(password)
            new_user.hold()
            return new_user
        else:
            return None

    def is_administartor(self):
        return self.has_privilege('admin')

    def is_receiver_existent(self, receiver_id):
        user = self.find_by(id=receiver_id)
        if user is not None:
            return True
        else:
            return False

    def all_sent_mail(self):
        mails = Mail.find_all(sender_id=self.id)
        return mails

    def all_received_mail(self):
        mails = Mail.find_all(receiver_id=self.id)
        return mails

    @staticmethod
    def hashed_password(password):
        # encode to bytes object
        pwd = password.encode('ascii')
        p = hashlib.sha512(pwd)
        # get back digest str
        return p.hexdigest()

    @staticmethod
    def salted_password(password):
        def sha512(ascii_str):
            return hashlib.sha512(ascii_str.encode('ascii')).hexdigest()
        pwd1 = sha512(password)
        pwd2 = sha512(pwd1 + salt)
        return pwd2

routes/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    session,
    flash,
)

from models.user import User

from routes import current_user

from utils import log


main = Blueprint('auth', __name__)

@main.route('/')
def index():
    return render_template('/auth/registerLogin.html')


@main.route('/loginout', methods=['POST'])
def login_out():
    form = request.form
    user = current_user()
    user_id = form.get('id', None)
    if user_id is not None:
        user_id = int(user_id)
        if user.id == user_id:
            session.pop('user_id', None)
            return redirect(url_for('.index'))    
    flash('未成功退出')
    return redirect(url_for('user.index', username=user.username))


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    new_user = User.register(form)
    if new_user is  None:
        flash('未注册成功， 用户名不合法或已被注册')
    else:
        flash('注册成功, 尝试登入吧')
    return redirect(url_for('.index'))


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    user = User.validate_login(form)
    if user is None:
        flash('登入失败，用户名或密码不正确')
        return redirect(url_for('.index'))
    else:
        session['user_id'] = user.id
        session.permanent = True
        username = user.__dict__['username']
        return redirect(url_for('user.index', username=username))

routes/index.py
from flask import (
    Blueprint,
    render_template,
    request,
)

from models.post import Post
from models.board import Board
from models import Pagination

from utils import (
    log,
    find_all_and_separate,
)


main = Blueprint('index', __name__)

@main.route('/')
def index():
    boards = Board.all()
    # you can set the quantity of unreplied_post by list slicing
    unreplied_posts = [p for p in Post.cache_all() if len(p.replies()) == 0]
    board_name = request.args.get('tab', '全部')
    # current_page is str passed from url
    # page 1 by default
    current_page = int(request.args.get('page', 1))
    if board_name == '全部':
        # top_posts = Post.find_all(top=True)
        # ordinary_posts = Post.find_all(top=False)
        # for performance
        ordinary_posts = Post.cache_all()
        top_posts = find_all_and_separate(ordinary_posts, top=True)
        top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
        ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
        sorted_posts = top_posts + ordinary_posts
    else:
        board = Board.find_by(name=board_name)
        if board is not None:
            # posts = Post.find_all(board_id=board.id)
            # top_posts = [p for p in posts if p.top == True]
            # ordinary_posts = [p for p in posts if p.top == False]
            # for performance
            ordinary_posts = Post.find_all(board_id=board.id)
            top_posts = find_all_and_separate(ordinary_posts, top=True)
            top_posts = sorted(top_posts, key=lambda post: post.ct, reverse=True)
            ordinary_posts = sorted(ordinary_posts, key=lambda post: post.ct, reverse=True)
            sorted_posts = top_posts + ordinary_posts
            # print('sorted_posts', len(sorted_posts))
        else:
            # in order to keep the consistency down here
            # we give the sorted_posts empty list
            sorted_posts = []
    page = Pagination(len(sorted_posts), current_page)
    data = page.data_by_page(sorted_posts)
    return render_template('index.html', data=data, page=page, unreplied_posts=unreplied_posts, boards=boards)

routes/mail.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    flash,
    request,
    abort,
)

from routes import current_user

from models.mail import Mail

from utils import log


main = Blueprint('mail', __name__)

@main.route('/')
def index():
    user = current_user()
    if user is not None:
        sent_mail = user.all_sent_mail()
        received_mail = user.all_received_mail()
        return render_template('/mail/mail.html', user=user, sent_mail=sent_mail, received_mail=received_mail)
    else:
        flash('要先登入才能发私信哦')
        return redirect(url_for('auth.index'))


@main.route('/send', methods=['POST'])
def send():
    form = request.form
    user = current_user()
    if user.is_receiver_existent(int(form.get('receiver_id'))):
        new_mail = Mail.new(form, sender_id=user.id)
        new_mail.hold()
    else:
        flash('没有此用户')
    return redirect(url_for('.index'))

@main.route('/detail')
def detail():
    m_id = request.args.get('id', None)
    if m_id is not None:
        m_id = int(m_id)
        mail = Mail.find_by(id=m_id)
        user = current_user()
        if mail is not None and (mail.sender_id == user.id or mail.receiver_id == user.id):
            if mail.receiver_id == user.id:
                mail.read()
            return render_template('/mail/detail.html', mail=mail, user=user)
    return abort(404)

routes/user.py
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    send_from_directory,
    redirect,
    abort,
)

from models.user import User
from models.post import Post
from models.reply import Reply

import os

from werkzeug.utils import secure_filename

from config import upload_folder

from utils import log

from routes import (
    allowed_file,
    current_user,
)


main = Blueprint('user', __name__)

@main.route('/<string:username>')
def index(username):
    user = User.find_by(username=username)
    if user is not None:
        is_self = bool(current_user() is not None and current_user().id == user.id)
        posts = Post.find_all(user_id=user.id)
        replies = Reply.find_all(user_id=user.id)
        return render_template('user/profile.html', user=user, is_self=is_self, posts=posts, replies=replies)
    else:
        return abort(404)


@main.route('/signature/update', methods=['POST'])
def update_signature():
    form = request.form
    user = User.find_by(id=int(form.get('id')))
    if user is not None:
        user.signature = form.get('signature', user.signature)
        user.hold()
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/add', methods=['POST'])
def upload_headportrait():
    file = request.files['file']
    user = current_user()
    if file and allowed_file(file.filename):
        # not consider the conditon filename is not secure 
        filename = secure_filename(file.filename)
        user_id = user.__dict__['id']
        filename = filename.rsplit('.', 1)[0] +  str(user_id) + '.' + filename.rsplit('.', 1)[1]
        file.save(os.path.join(upload_folder, filename))
    return redirect(url_for('.index', username=user.username))


@main.route('/headportrait/<int:u_id>')
def headportrait(u_id):
    file_list = os.listdir(upload_folder)
    for file in file_list:
        # do't forget turn to int 
        if u_id == int(file.rsplit('.', 1)[0][-1]):
            return send_from_directory(upload_folder, file)
    return abort(404)

templates/user/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>bbs club专业的问答社区</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
</head>
<body>
    <!-- navbar -->
    <div class='navbar'>
        <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href="{{ url_for('index.index') }}">
                <img style="HEIGHT: inherit" src="{{ url_for('static', filename='1170859.gif') }}" />
            </a>
            <!-- call google search -->
            <form id='search_form' class='navbar-search' action="http://www.google.com/search">
                <input type='text' id='q' name='q' class='search-query span3' value=''/>
            </form>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('index.index') }}">首页</a></li>
                
                <li><a href='/getstart'>新手入门</a></li>
                <li><a href='/api'>API</a></li>
                
                <li><a href="/about" target="">关于</a></li>
                
                <li><a href="{{ url_for('auth.index') }}">注册</a></li>
                <li><a href="{{ url_for('auth.index') }}">登录</a></li>
            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
        </div>
    </div>
    <div id="main">
        <div id="content">
            <div>
                <h1>用户资料页面</h1>
                <div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item active">用户名: {{ user.username }}</li>
                        <li class="list-group-item active">ID: {{ user.id }}</li>
                        {% if is_self %}
                        <li class="list-group-item active">安全摘要密码: {{ user.password }}</li>
                        {% endif %}
                        <li class="list-group-item active">个性签名: {{ user.signature }}</li>
                        {% if is_self %}
                        <form action="{{ url_for('user.update_signature') }}" method="post">
                            <input type="hidden" name="id" value="{{ user.id }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="text" name="signature" placeholder="换个新签名?">
                            <input type="submit" value="更换">
                        </form>
                        <form action="{{ url_for('auth.login_out') }}" method="post">
                            <input type="hidden" name="id" value="{{ user.id }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" value="退出登入">
                        </form>
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <ul class=flashes>
                            {% for message in messages %}
                            <li>{{ message }}</li>
                            {% endfor %}
                            </ul>
                            {% endif %}
                        {% endwith %}
                        {% endif %}
                    </ul>
                </div>
                <a href="{{ url_for('mail.index') }}">私信</a>
                <div>
                    大头贴 <br>
                    <img src="{{ url_for('.headportrait', u_id=user.id) }}" alt="还未上传头像">
                </div>
                {% if is_self %}
                上传或更换新头像:
                <form method="POST" action=" {{ url_for('.upload_headportrait') }} " enctype="multipart/form-data">
                    <div class="custom-file">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <input type="file" name="file" class="custom-file-input" id="customFile">
                        <input type="submit" value="Upload">
                    </div>
                </form>  
                {% endif %}   
                <h3>最近创建的话题</h3>
                <div>
                    <ul class="list-group posts">
                        {% for p in posts %}
                        <li class="list-group-item" data-id="{{ p.id }}" >{{ p.board().name }}: {{ p.title }} {{ p.format_ct() }} {% if is_self %}<button class="delete-post">删除</button>{% endif %} </li>
                        {% endfor %}
                    </ul>
                </div>
                <h3>最近的回复</h3>
                <div>
                    <ul class="list-group">
                        {% for r in replies %}
                        <li class="list-group-item">{{ r.content }} {{ r.format_ct() }} </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/js/util.js"></script>
    <script src="/static/js/post.js"></script>
</body>
</html>